import { d as createAstro, c as createComponent, r as renderTemplate, g as renderComponent, l as renderHead, e as addAttribute } from '../astro_cjlGYYx7.mjs';
import 'kleur/colors';
import 'clsx';
import { a as $$Footer, b as $$Header, c as $$BaseHead, S as SITE_TITLE, d as SITE_DESCRIPTION, g as getCollection, e as $$FormattedDate } from './__xmN8ao_i.mjs';
/* empty css                          */

/** @returns {void} */

function run(fn) {
	return fn();
}

function blank_object() {
	return Object.create(null);
}

/**
 * @param {Function[]} fns
 * @returns {void}
 */
function run_all(fns) {
	fns.forEach(run);
}

let current_component;

/** @returns {void} */
function set_current_component(component) {
	current_component = component;
}

// general each functions:

function ensure_array_like(array_like_or_iterator) {
	return array_like_or_iterator?.length !== undefined
		? array_like_or_iterator
		: Array.from(array_like_or_iterator);
}

const ATTR_REGEX = /[&"]/g;
const CONTENT_REGEX = /[&<]/g;

/**
 * Note: this method is performance sensitive and has been optimized
 * https://github.com/sveltejs/svelte/pull/5701
 * @param {unknown} value
 * @returns {string}
 */
function escape(value, is_attr = false) {
	const str = String(value);
	const pattern = is_attr ? ATTR_REGEX : CONTENT_REGEX;
	pattern.lastIndex = 0;
	let escaped = '';
	let last = 0;
	while (pattern.test(str)) {
		const i = pattern.lastIndex - 1;
		const ch = str[i];
		escaped += str.substring(last, i) + (ch === '&' ? '&amp;' : ch === '"' ? '&quot;' : '&lt;');
		last = i + 1;
	}
	return escaped + str.substring(last);
}

/** @returns {string} */
function each(items, fn) {
	items = ensure_array_like(items);
	let str = '';
	for (let i = 0; i < items.length; i += 1) {
		str += fn(items[i], i);
	}
	return str;
}

let on_destroy;

/** @returns {{ render: (props?: {}, { $$slots, context }?: { $$slots?: {}; context?: Map<any, any>; }) => { html: any; css: { code: string; map: any; }; head: string; }; $$render: (result: any, props: any, bindings: any, slots: any, context: any) => any; }} */
function create_ssr_component(fn) {
	function $$render(result, props, bindings, slots, context) {
		const parent_component = current_component;
		const $$ = {
			on_destroy,
			context: new Map(context || (parent_component ? parent_component.$$.context : [])),
			// these will be immediately discarded
			on_mount: [],
			before_update: [],
			after_update: [],
			callbacks: blank_object()
		};
		set_current_component({ $$ });
		const html = fn(result, props, bindings, slots);
		set_current_component(parent_component);
		return html;
	}
	return {
		render: (props = {}, { $$slots = {}, context = new Map() } = {}) => {
			on_destroy = [];
			const result = { title: '', head: '', css: new Set() };
			const html = $$render(result, props, {}, $$slots, context);
			run_all(on_destroy);
			return {
				html,
				css: {
					code: Array.from(result.css)
						.map((css) => css.code)
						.join('\n'),
					map: null // TODO
				},
				head: result.title + result.head
			};
		},
		$$render
	};
}

/* C:/Users/fife/webdev/bpmtools2/src/components/svelte/SubBassComp.svelte generated by Svelte v4.2.8 */

const SubBassComp = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	const data = [
		{ note: 'C', freq: '32.7', time: '31' },
		{ note: 'C#/Db', freq: '34.6', time: '29' },
		{ note: 'D', freq: '36.7', time: '27' },
		{ note: 'D#/Eb', freq: '38.9', time: '26' },
		{ note: 'E', freq: '41.2', time: '24' },
		{ note: 'F', freq: '43.6', time: '23' },
		{ note: 'F#/Gb', freq: '46.3', time: '22' },
		{ note: 'G', freq: '49.0', time: '20' },
		{ note: 'G#/Ab', freq: '51.9', time: '19' },
		{ note: 'A', freq: '55.0', time: '18' },
		{ note: 'A#/Bb', freq: '58.3', time: '17' },
		{ note: 'B', freq: '61.7', time: '16' }
	];

	return `<section class="subbass-compression"><table><thead data-svelte-h="svelte-z2ovv9"><tr><th>Note</th> <th>Frequency</th> <th>Time</th></tr></thead> <tbody>${each(data, row => {
		return `<tr><td>${escape(row.note)}<sub data-svelte-h="svelte-gk2sgj">1</sub></td> <td>${escape(row.freq)}<span class="table-units" data-svelte-h="svelte-qmsd1">Hz</span></td> <td>${escape(row.time)}<span class="table-units" data-svelte-h="svelte-5a58sz">ms</span></td> </tr>`;
	})}</tbody></table> <p data-svelte-h="svelte-1bguwm8">This table provides the time it takes to complete a single sub bass cycle. It may be beneficial for applying compression or layering in the sub-bass range.</p></section>`;
});

/* C:/Users/fife/webdev/bpmtools2/src/components/svelte/NoteFreqs.svelte generated by Svelte v4.2.8 */

const NoteFreqs = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	const FREQTABLE = [
		{ note: 'C', freq: 16.4, range: 'sub bass' },
		{
			note: 'C# / Db',
			freq: 17.3,
			range: 'sub bass'
		},
		{ note: 'D', freq: 18.4, range: 'sub bass' },
		{
			note: 'D# / Eb',
			freq: 19.4,
			range: 'sub bass'
		},
		{ note: 'E', freq: 20.6, range: 'sub bass' },
		{ note: 'F', freq: 21.8, range: 'sub bass' },
		{
			note: 'F# / Gb',
			freq: 23.1,
			range: 'sub bass'
		},
		{ note: 'G', freq: 24.5, range: 'sub bass' },
		{
			note: 'G# / Ab',
			freq: 26.0,
			range: 'sub bass'
		},
		{ note: 'A', freq: 27.5, range: 'sub bass' },
		{
			note: 'A# / Bb',
			freq: 29.1,
			range: 'sub bass'
		},
		{ note: 'B', freq: 30.9, range: 'sub bass' },
		{ note: 'C', freq: 32.7, range: 'sub bass' },
		{
			note: 'C# / Db',
			freq: 34.6,
			range: 'sub bass'
		},
		{ note: 'D', freq: 36.7, range: 'sub bass' },
		{
			note: 'D# / Eb',
			freq: 38.9,
			range: 'sub bass'
		},
		{ note: 'E', freq: 41.2, range: 'sub bass' },
		{ note: 'F', freq: 43.6, range: 'sub bass' },
		{
			note: 'F# / Gb',
			freq: 46.3,
			range: 'sub bass'
		},
		{ note: 'G', freq: 49.0, range: 'sub bass' },
		{
			note: 'G# / Ab',
			freq: 51.9,
			range: 'sub bass'
		},
		{ note: 'A', freq: 55.0, range: 'sub bass' },
		{
			note: 'A# / Bb',
			freq: 58.3,
			range: 'sub bass'
		},
		{ note: 'B', freq: 61.7, range: 'sub bass' },
		{ note: 'C', freq: 65.4, range: 'bass' },
		{
			note: 'C# / Db',
			freq: 69.3,
			range: 'bass'
		},
		{ note: 'D', freq: 73.4, range: 'bass' },
		{
			note: 'D# / Eb',
			freq: 77.8,
			range: 'bass'
		},
		{ note: 'E', freq: 82.4, range: 'bass' },
		{ note: 'F', freq: 87.3, range: 'bass' },
		{
			note: 'F# / Gb',
			freq: 92.5,
			range: 'bass'
		},
		{ note: 'G', freq: 98.0, range: 'bass' },
		{
			note: 'G# / Ab',
			freq: 103.8,
			range: 'bass'
		},
		{ note: 'A', freq: 110.0, range: 'bass' },
		{
			note: 'A# / Bb',
			freq: 116.5,
			range: 'bass'
		},
		{ note: 'B', freq: 123.5, range: 'bass' },
		{
			note: 'C',
			freq: 130.8,
			range: 'upper bass'
		},
		{
			note: 'C# / Db',
			freq: 138.6,
			range: 'upper bass'
		},
		{
			note: 'D',
			freq: 146.8,
			range: 'upper bass'
		},
		{
			note: 'D# / Eb',
			freq: 155.6,
			range: 'upper bass'
		},
		{
			note: 'E',
			freq: 164.8,
			range: 'upper bass'
		},
		{
			note: 'F',
			freq: 174.6,
			range: 'upper bass'
		},
		{
			note: 'F# / Gb',
			freq: 185.0,
			range: 'upper bass'
		},
		{
			note: 'G',
			freq: 196.0,
			range: 'upper bass'
		},
		{
			note: 'G# / Ab',
			freq: 207.7,
			range: 'upper bass'
		},
		{
			note: 'A',
			freq: 220.0,
			range: 'upper bass'
		},
		{
			note: 'A# / Bb',
			freq: 233.1,
			range: 'upper bass'
		},
		{
			note: 'B',
			freq: 246.9,
			range: 'upper bass'
		},
		{
			note: 'C',
			freq: 261.6,
			range: 'lower midrange'
		},
		{
			note: 'C# / Db',
			freq: 277.2,
			range: 'lower midrange'
		},
		{
			note: 'D',
			freq: 293.7,
			range: 'lower midrange'
		},
		{
			note: 'D# / Eb',
			freq: 311.1,
			range: 'lower midrange'
		},
		{
			note: 'E',
			freq: 329.6,
			range: 'lower midrange'
		},
		{
			note: 'F',
			freq: 349.2,
			range: 'lower midrange'
		},
		{
			note: 'F# / Gb',
			freq: 370.0,
			range: 'lower midrange'
		},
		{
			note: 'G',
			freq: 392.0,
			range: 'lower midrange'
		},
		{
			note: 'G# / Ab',
			freq: 415.3,
			range: 'lower midrange'
		},
		{
			note: 'A',
			freq: 440.0,
			range: 'lower midrange'
		},
		{
			note: 'A# / Bb',
			freq: 466.2,
			range: 'lower midrange'
		},
		{
			note: 'B',
			freq: 493.9,
			range: 'lower midrange'
		},
		{
			note: 'C',
			freq: 523.3,
			range: 'middle midrange'
		},
		{
			note: 'C# / Db',
			freq: 554.4,
			range: 'middle midrange'
		},
		{
			note: 'D',
			freq: 587.3,
			range: 'middle midrange'
		},
		{
			note: 'D# / Eb',
			freq: 622.3,
			range: 'middle midrange'
		},
		{
			note: 'E',
			freq: 659.3,
			range: 'middle midrange'
		},
		{
			note: 'F',
			freq: 698.5,
			range: 'middle midrange'
		},
		{
			note: 'F# / Gb',
			freq: 740.0,
			range: 'middle midrange'
		},
		{
			note: 'G',
			freq: 784.0,
			range: 'middle midrange'
		},
		{
			note: 'G# / Ab',
			freq: 830.6,
			range: 'middle midrange'
		},
		{
			note: 'A',
			freq: 880.0,
			range: 'middle midrange'
		},
		{
			note: 'A# / Bb',
			freq: 923.3,
			range: 'middle midrange'
		},
		{
			note: 'B',
			freq: 987.8,
			range: 'middle midrange'
		},
		{
			note: 'C',
			freq: 1046.5,
			range: 'upper midrange'
		},
		{
			note: 'C# / Db',
			freq: 1108.7,
			range: 'upper midrange'
		},
		{
			note: 'D',
			freq: 1174.7,
			range: 'upper midrange'
		},
		{
			note: 'D# / Eb',
			freq: 1244.5,
			range: 'upper midrange'
		},
		{
			note: 'E',
			freq: 1318.5,
			range: 'upper midrange'
		},
		{
			note: 'F',
			freq: 1396.9,
			range: 'upper midrange'
		},
		{
			note: 'F# / Gb',
			freq: 1480.0,
			range: 'upper midrange'
		},
		{
			note: 'G',
			freq: 1568.0,
			range: 'upper midrange'
		},
		{
			note: 'G# / Ab',
			freq: 1661.2,
			range: 'upper midrange'
		},
		{
			note: 'A',
			freq: 1760.0,
			range: 'upper midrange'
		},
		{
			note: 'A# / Bb',
			freq: 1864.7,
			range: 'upper midrange'
		},
		{
			note: 'B',
			freq: 1975.5,
			range: 'upper midrange'
		},
		{
			note: 'C',
			freq: 2093.0,
			range: 'present midrange'
		},
		{
			note: 'C# / Db',
			freq: 2217.5,
			range: 'present midrange'
		},
		{
			note: 'D',
			freq: 2349.3,
			range: 'present midrange'
		},
		{
			note: 'D# / Eb',
			freq: 2489.0,
			range: 'present midrange'
		},
		{
			note: 'E',
			freq: 2637.0,
			range: 'present midrange'
		},
		{
			note: 'F',
			freq: 2793.8,
			range: 'present midrange'
		},
		{
			note: 'F# / Gb',
			freq: 2960.0,
			range: 'present midrange'
		},
		{
			note: 'G',
			freq: 3136.0,
			range: 'present midrange'
		},
		{
			note: 'G# / Ab',
			freq: 3322.4,
			range: 'present midrange'
		},
		{
			note: 'A',
			freq: 3520.0,
			range: 'present midrange'
		},
		{
			note: 'A# / Bb',
			freq: 3729.3,
			range: 'present midrange'
		},
		{
			note: 'B',
			freq: 3951.1,
			range: 'present midrange'
		},
		{
			note: 'C',
			freq: 4186.0,
			range: 'high end'
		},
		{
			note: 'C# / Db',
			freq: 4434.9,
			range: 'high end'
		},
		{
			note: 'D',
			freq: 4698.6,
			range: 'high end'
		},
		{
			note: 'D# / Eb',
			freq: 4978.0,
			range: 'high end'
		},
		{
			note: 'E',
			freq: 5274.0,
			range: 'high end'
		},
		{
			note: 'F',
			freq: 5587.6,
			range: 'high end'
		},
		{
			note: 'F# / Gb',
			freq: 5919.9,
			range: 'high end'
		},
		{
			note: 'G',
			freq: 6271.9,
			range: 'high end'
		},
		{
			note: 'G# / Ab',
			freq: 6644.9,
			range: 'high end'
		},
		{
			note: 'A',
			freq: 7040.0,
			range: 'high end'
		},
		{
			note: 'A# / Bb',
			freq: 7458.6,
			range: 'high end'
		},
		{
			note: 'B',
			freq: 7902.1,
			range: 'high end'
		}
	];

	return `<section class="note-frequencies"><table><thead data-svelte-h="svelte-zaviff"><tr><th>Note (A4 = 440)</th> <th>Frequency (Hz)</th> <th>Range</th></tr></thead> <tbody>${each(FREQTABLE, (row, index) => {
		return `<tr><td>${escape(row.note)}<sub>${escape(Math.floor(index / 12))}</sub></td> <td>${escape(row.freq)}<span class="table-units" data-svelte-h="svelte-qmsd1">Hz</span></td> <td>${escape(row.range)}</td> </tr>`;
	})}</tbody></table> <p data-svelte-h="svelte-am4kz6">A table of musical notes and their corresponding frequencies (when A=440). This is useful for instrumentation ranges and EQing. It is generally best practice to roll off the lows between 20 and 40 Hertz.</p></section>`;
});

/* C:/Users/fife/webdev/bpmtools2/src/components/svelte/ToDo.svelte generated by Svelte v4.2.8 */

const ToDo = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<ul data-svelte-h="svelte-1alpf6d"><li>Toggle between ms / samples</li> <li>Add piano roll with scale keys highlighted</li> <li>Highlight corresponding frequency notes in the table</li> <li>dark/light/color modes</li> <li>ms/sample converter</li></ul>`;
});

var __freeze = Object.freeze;
var __defProp = Object.defineProperty;
var __template = (cooked, raw) => __freeze(__defProp(cooked, "raw", { value: __freeze(raw || cooked.slice()) }));
var _a;
const $$Astro$1 = createAstro("https://bpmtools.net");
const $$Index$1 = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$1, $$props, $$slots);
  Astro2.self = $$Index$1;
  return renderTemplate(_a || (_a = __template(['<html lang="en"> <head><script async src="https://us.umami.is/script.js" data-website-id="65e7053a-c193-407d-9edf-252602027eb6"><\/script>', '<link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png"><link rel="manifest" href="/favicons/site.webmanifest"><link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5"><meta name="msapplication-TileColor" content="#da532c"><meta name="theme-color" content="#ffffff">', '</head> <body class="web"> ', " ", " ", ' <main> <div class="main-container"> <section class="all-modules"> <details> <summary> <h2>Mode / scale reference (WIP)</h2> </summary> ', ' <span><a href="https://en.wikipedia.org/wiki/Mode_(music)" target="_blank" rel="noopener noreferrer">Modes</a> | <a href="https://en.wikipedia.org/wiki/Chord_(music)" target="_blank" rel="noopener noreferrer">Chords</a> | <a href="https://en.wikipedia.org/wiki/Circle_of_fifths" target="_blank" rel="noopener noreferrer">Circle of fifths</a></span> </details> <details> <summary> <h2>\nDelay / pre-delay calculator\n</h2> </summary> ', " </details> <details> <summary> <h2>\nLFO / Hertz calculator\n</h2> </summary> ", " </details> <details> <summary> <h2>\nSub-bass compression attack minimums\n</h2> </summary> ", " </details> <details> <summary> <h2>\nMusical note frequencies\n</h2> </summary> ", " </details> <details> <summary> <h2>\nTo Do\n</h2> <hgroup>\nUpdates that need to be made. Short term roadmap.\n</hgroup> </summary> ", " </details> <details> <summary> <h2>Millisecond --> Samples (WIP)</h2> </summary> ", " </details> </section> </div> </main> ", " </body></html>"])), renderComponent($$result, "BaseHead", $$BaseHead, { "title": "BPM Tools", "description": SITE_DESCRIPTION }), renderHead(), renderComponent($$result, "Header", $$Header, { "title": SITE_TITLE }), renderComponent($$result, "BpmSettings", null, { "client:only": "svelte", "client:component-hydration": "only", "client:component-path": "C:/Users/fife/webdev/bpmtools2/src/components/svelte/BpmSettings.svelte", "client:component-export": "default" }), renderComponent($$result, "BpmInput", null, { "client:only": "svelte", "client:component-hydration": "only", "client:component-path": "C:/Users/fife/webdev/bpmtools2/src/components/svelte/BpmInput.svelte", "client:component-export": "default" }), renderComponent($$result, "ModeReference", null, { "client:only": "svelte", "client:component-hydration": "only", "client:component-path": "C:/Users/fife/webdev/bpmtools2/src/components/svelte/ModeReference.svelte", "client:component-export": "default" }), renderComponent($$result, "DelayCalc", null, { "client:only": "svelte", "client:component-hydration": "only", "client:component-path": "C:/Users/fife/webdev/bpmtools2/src/components/svelte/DelayCalc.svelte", "client:component-export": "default" }), renderComponent($$result, "LfoHertz", null, { "client:only": "svelte", "client:component-hydration": "only", "client:component-path": "C:/Users/fife/webdev/bpmtools2/src/components/svelte/LfoHertz.svelte", "client:component-export": "default" }), renderComponent($$result, "SubBassComp", SubBassComp, {}), renderComponent($$result, "NoteFreqs", NoteFreqs, {}), renderComponent($$result, "ToDo", ToDo, {}), renderComponent($$result, "MsSampleConvert", null, { "client:only": "svelte", "client:component-hydration": "only", "client:component-path": "C:/Users/fife/webdev/bpmtools2/src/components/svelte/MsSampleConvert.svelte", "client:component-export": "default" }), renderComponent($$result, "Footer", $$Footer, {}));
}, "C:/Users/fife/webdev/bpmtools2/src/pages/index.astro", void 0);

const $$file$1 = "C:/Users/fife/webdev/bpmtools2/src/pages/index.astro";
const $$url$1 = "";

const index$1 = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
	__proto__: null,
	default: $$Index$1,
	file: $$file$1,
	url: $$url$1
}, Symbol.toStringTag, { value: 'Module' }));

const $$Astro = createAstro("https://bpmtools.net");
const $$Index = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Index;
  const posts = (await getCollection("blog")).sort(
    (a, b) => a.data.pubDate.valueOf() - b.data.pubDate.valueOf()
  );
  return renderTemplate`<html lang="en" data-astro-cid-5tznm7mj> <head>${renderComponent($$result, "BaseHead", $$BaseHead, { "title": SITE_TITLE, "description": SITE_DESCRIPTION, "data-astro-cid-5tznm7mj": true })}${renderHead()}</head> <body data-astro-cid-5tznm7mj> ${renderComponent($$result, "Header", $$Header, { "data-astro-cid-5tznm7mj": true })} <main data-astro-cid-5tznm7mj> <section data-astro-cid-5tznm7mj> <ul data-astro-cid-5tznm7mj> ${posts.map((post) => renderTemplate`<li data-astro-cid-5tznm7mj> <a${addAttribute(`/blog/${post.slug}/`, "href")} data-astro-cid-5tznm7mj> <img${addAttribute(720, "width")}${addAttribute(360, "height")}${addAttribute(post.data.heroImage, "src")} alt="" data-astro-cid-5tznm7mj> <h4 class="title" data-astro-cid-5tznm7mj>${post.data.title}</h4> <p class="date" data-astro-cid-5tznm7mj> ${renderComponent($$result, "FormattedDate", $$FormattedDate, { "date": post.data.pubDate, "data-astro-cid-5tznm7mj": true })} </p> </a> </li>`)} </ul> </section> </main> ${renderComponent($$result, "Footer", $$Footer, { "data-astro-cid-5tznm7mj": true })} </body></html>`;
}, "C:/Users/fife/webdev/bpmtools2/src/pages/blog/index.astro", void 0);

const $$file = "C:/Users/fife/webdev/bpmtools2/src/pages/blog/index.astro";
const $$url = "/blog";

const index = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
	__proto__: null,
	default: $$Index,
	file: $$file,
	url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

export { index as a, index$1 as i };
